//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.WCFServiceLib {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceLib.IWCFService")]
    public interface IWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/AddUser", ReplyAction="http://tempuri.org/IWCFService/AddUserResponse")]
        int AddUser(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/AddUser", ReplyAction="http://tempuri.org/IWCFService/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/AddAddress", ReplyAction="http://tempuri.org/IWCFService/AddAddressResponse")]
        int AddAddress(string city, string street, int build, int flat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/AddAddress", ReplyAction="http://tempuri.org/IWCFService/AddAddressResponse")]
        System.Threading.Tasks.Task<int> AddAddressAsync(string city, string street, int build, int flat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/AddOrder", ReplyAction="http://tempuri.org/IWCFService/AddOrderResponse")]
        int AddOrder(string goodname, int UserId, int AddrId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/AddOrder", ReplyAction="http://tempuri.org/IWCFService/AddOrderResponse")]
        System.Threading.Tasks.Task<int> AddOrderAsync(string goodname, int UserId, int AddrId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/RemoveUser", ReplyAction="http://tempuri.org/IWCFService/RemoveUserResponse")]
        bool RemoveUser(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/RemoveUser", ReplyAction="http://tempuri.org/IWCFService/RemoveUserResponse")]
        System.Threading.Tasks.Task<bool> RemoveUserAsync(int UserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/RemoveAddress", ReplyAction="http://tempuri.org/IWCFService/RemoveAddressResponse")]
        bool RemoveAddress(int AddrId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/RemoveAddress", ReplyAction="http://tempuri.org/IWCFService/RemoveAddressResponse")]
        System.Threading.Tasks.Task<bool> RemoveAddressAsync(int AddrId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/RemoveOrder", ReplyAction="http://tempuri.org/IWCFService/RemoveOrderResponse")]
        bool RemoveOrder(int OrdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/RemoveOrder", ReplyAction="http://tempuri.org/IWCFService/RemoveOrderResponse")]
        System.Threading.Tasks.Task<bool> RemoveOrderAsync(int OrdId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/AddAddressUserLink", ReplyAction="http://tempuri.org/IWCFService/AddAddressUserLinkResponse")]
        int AddAddressUserLink(int UserId, int AddrId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/AddAddressUserLink", ReplyAction="http://tempuri.org/IWCFService/AddAddressUserLinkResponse")]
        System.Threading.Tasks.Task<int> AddAddressUserLinkAsync(int UserId, int AddrId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/RemoveAddressUserLink", ReplyAction="http://tempuri.org/IWCFService/RemoveAddressUserLinkResponse")]
        bool RemoveAddressUserLink(int LinkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/RemoveAddressUserLink", ReplyAction="http://tempuri.org/IWCFService/RemoveAddressUserLinkResponse")]
        System.Threading.Tasks.Task<bool> RemoveAddressUserLinkAsync(int LinkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetData", ReplyAction="http://tempuri.org/IWCFService/GetDataResponse")]
        string GetData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFService/GetData", ReplyAction="http://tempuri.org/IWCFService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFServiceChannel : WCFClient.WCFServiceLib.IWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFServiceClient : System.ServiceModel.ClientBase<WCFClient.WCFServiceLib.IWCFService>, WCFClient.WCFServiceLib.IWCFService {
        
        public WCFServiceClient() {
        }
        
        public WCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddUser(string name) {
            return base.Channel.AddUser(name);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(string name) {
            return base.Channel.AddUserAsync(name);
        }
        
        public int AddAddress(string city, string street, int build, int flat) {
            return base.Channel.AddAddress(city, street, build, flat);
        }
        
        public System.Threading.Tasks.Task<int> AddAddressAsync(string city, string street, int build, int flat) {
            return base.Channel.AddAddressAsync(city, street, build, flat);
        }
        
        public int AddOrder(string goodname, int UserId, int AddrId) {
            return base.Channel.AddOrder(goodname, UserId, AddrId);
        }
        
        public System.Threading.Tasks.Task<int> AddOrderAsync(string goodname, int UserId, int AddrId) {
            return base.Channel.AddOrderAsync(goodname, UserId, AddrId);
        }
        
        public bool RemoveUser(int UserId) {
            return base.Channel.RemoveUser(UserId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveUserAsync(int UserId) {
            return base.Channel.RemoveUserAsync(UserId);
        }
        
        public bool RemoveAddress(int AddrId) {
            return base.Channel.RemoveAddress(AddrId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAddressAsync(int AddrId) {
            return base.Channel.RemoveAddressAsync(AddrId);
        }
        
        public bool RemoveOrder(int OrdId) {
            return base.Channel.RemoveOrder(OrdId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveOrderAsync(int OrdId) {
            return base.Channel.RemoveOrderAsync(OrdId);
        }
        
        public int AddAddressUserLink(int UserId, int AddrId) {
            return base.Channel.AddAddressUserLink(UserId, AddrId);
        }
        
        public System.Threading.Tasks.Task<int> AddAddressUserLinkAsync(int UserId, int AddrId) {
            return base.Channel.AddAddressUserLinkAsync(UserId, AddrId);
        }
        
        public bool RemoveAddressUserLink(int LinkId) {
            return base.Channel.RemoveAddressUserLink(LinkId);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAddressUserLinkAsync(int LinkId) {
            return base.Channel.RemoveAddressUserLinkAsync(LinkId);
        }
        
        public string GetData() {
            return base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
    }
}
